### ISSUE TITLE
Select Objectが機能していません

### ISSUE THREAD

**Issue by InamuraJIN** [nepia11/rename_tool#1]
選択外オブジェクトもチェックしているようです
環境：Blender3.0

要望（無視してもらっておｋです）
どのオブジェクト、どのデータブロックに含まれた名前なのかを記載してもらえると嬉しいかも？
全角文字が発見された時の内容はRenameパネルに表示されているので、Message boxの表示は必要ない気がします（エラーの時によく見るボックスなので一瞬ビックリします）

**Comment by nepia11** [comment]
@InamuraJIN ものすごく遅レスになるんですが返信します
・select objectsのオプションの現在の実装は、「チェック実行時に非ascii文字を含む名前のオブジェクトを選択するか」どうかを切り替えます。 True時はチェック時にオブジェクトを選択します
・Message boxはチェック実行時に見つけた非ascii文字を含むデータブロックを表示していますが必要なければ除去します
・チェック実行時に見つけた非ascii文字を含むデータブロックはinfoにも一応表示していますが見逃しやすいと言われればたしかにそうなのでパネルに表示するのはどうでしょう？

**Comment by nepia11** [comment]
#2
